### ISSUE TITLE
keyError

### ISSUE THREAD

**Issue by claman** [cleverdevil/ditchbook#4]
This is the output when I try to run `ingest`:

```
Traceback (most recent call last):
  File "bin/ingest", line 25, in <module>
    mf2 = process_post(post)
  File "/home/alex/Documents/ditchbook/ditchbook/ingest.py", line 94, in process_post
    mf2['properties']['content'] = [post['data'][0]['post']]
KeyError: 'post'
```

**Comment by cleverdevil** [comment]
Interesting. It looks like perhaps Facebook changed the structure/format of the export. I've just pushed an update that will catch the error, and print out some debugging information for me. Can you pull the update and then re-run `ingest`? Once you've done that, you should see some output that says 'Unexpected missing key "post" ->', followed by some data, which is what I need to figure out what's going on. If you could post that back here, that would be super helpful!

**Comment by claman** [comment]
Sorry for the delay. Here you go!

```
Unexpected missing key "post" ->
{'update_timestamp': 1478704676}
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Unexpected missing key "post" ->
{'update_timestamp': 1478673433}
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "bin/ingest", line 25, in <module>
    mf2 = process_post(post)
  File "/home/alex/Documents/ditchbook/ditchbook/ingest.py", line 74, in process_post
    'export/%s' % media['media']['uri']
KeyError: 'media'
```

**Comment by cleverdevil** [comment]
Thank you! That helped. I've made another change to give me even more information. If you could pull it down and run once again, I should have more clarity.

**Comment by claman** [comment]
```
--------------------------------------------------------------------------------
Unexpected missing key "post" ->
[{'update_timestamp': 1478704676}]
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Unexpected missing key "post" ->
[{'update_timestamp': 1478673433}]
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Unexpected missing key in media ->
{'external_context': {'name': 'Instagram photo â\x80¢ Oct 10, 2016 at 11:40pm UTC', 'url': 'https://www.instagram.com/p/BLZrTLhBwR79L4X0JRfafeQ4MeHR6dTBYh_UEA0/'}}
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Unexpected missing key in media ->
{'external_context': {'name': 'Instagram photo â\x80¢ Sep 4, 2016 at 7:09pm UTC', 'url': 'https://www.instagram.com/p/BJ8fnqYARH4w_A8YGpJ9Jqmgwc7Y0xKs5rF3To0/'}}
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Unexpected missing key in media ->
{'place': {'name': 'Laramie, Wyoming', 'coordinate': {'latitude': 41.3129, 'longitude': -105.587}, 'address': 'Laramie, Wyoming 82070', 'url': 'https://www.facebook.com/pages/Laramie-Wyoming/105667169467451'}}
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Unexpected missing key "post" ->
[{'update_timestamp': 1453870186}]
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Unexpected missing key "post" ->
[{'update_timestamp': 1447542305}]
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Unexpected missing key "post" ->
[{'update_timestamp': 1440606739}]
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Unexpected missing key "post" ->
[{'update_timestamp': 1438275584}]
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Unexpected missing key "post" ->
[{'update_timestamp': 1436292439}]
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Unexpected missing key "post" ->
[{'update_timestamp': 1425794422}]
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Unexpected missing key "post" ->
[{'update_timestamp': 1354662189}]
--------------------------------------------------------------------------------
```

**Comment by cleverdevil** [comment]
Cool, given that, it looks like I can cleanly "skip" all of that content. I've made one last change to ensure that any of this skipped content doesn't impact the overall ingest process. Pull and run once more, you'll still see the warnings about "unexpected missing key," but hopefully it'll exit cleanly, and you'll have a directory called `mf2` containing all of the content that *was* converted as MF2 JSON. Let me know if that happens. If so, you should be good to configure your micropub endpoint and move onto the next step!

**Comment by claman** [comment]
Sorry for the delay; it works! Thanks for the help.

**Comment by cleverdevil** [comment]
Awesome news @claman! Please do let me know once you've got your content migrated to your site, so I can check it out!
