### ISSUE TITLE
bin/ingest export 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by chrispederick** [cleverdevil/ditchbook#6]
When I run `bin/ingest export` I get the following error:

```
Traceback (most recent call last):
  File "bin/ingest", line 24, in <module>
    for post in posts.get('status_updates', []):
AttributeError: 'list' object has no attribute 'get'
```

This sounds like maybe a parsing error, but I also had to jump through some hoops to get Python working on my Mac so it's possible something is not quite right there either.

Any ideas?

**Comment by bekopharm** [comment]
[bin/ingest export ‘list’ object has no attribute ‘get’ · Issue #6 · cleverdevil/ditchbook](https://github.com/cleverdevil/ditchbook/issues/6) _( GitHub)_

&gt; When I run bin/ingest export I get the following error: Traceback (most recent call last): File "bin/ingest", line 24, in &lt;module&gt; for post in posts.get('status_updates', []…

Looks like FB changed it’s export format:

`[{"timestamp": 1566833332,"attachments": [],"data": [{"post": ""},{"update_timestamp": 1566833332}],"title": ""}]`

This is not what Ditchpost expects.

The posts file is also no longer _posts/your_posts.json_ but _posts/your_posts_01.json_

Also on

  * [ ](https://brid.gy/publish/github)
